// 汇编/X86Comp.fs和NASM生成的x86代码的C驱动程序。C driver for x86 code generated by Assembly/X86Comp.fs and NASM.
// 定义调用程序集的初始入口点（main）Defines the initial entrypoint (main) which calls the assembly
// 入口点（asm\u main）和实用程序函数（printc、printf、entrypoint (asm_main), and utility functions (printc, printf,
// checkargc）从程序集代码调用。checkargc) called from the assembly code.

// Originally by Niels Kokholm, March 2002
// sestoft@itu.dk * 2017-11-18

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

extern void asm_main(int,int*);

int printc(int c) { printf("%c", c); return c; }

int printi(int i) { printf("%d ", i); return i; }

void checkargc(int a, int b) { 
  if (a!=b) {
    printf("Wrong argument count: expected %d but got %d\n",a,b); 
    exit(1);
  }
}

int main(int argc, char **argv) {
  int i, args[63];
  for (i=1; i<argc; i++) 
    args[i-1] = atoi(argv[i]);
  asm_main(argc-1,args);
  printf("\nRan %.3f s\n",(clock())*1.0/CLOCKS_PER_SEC);
  exit(0);
}
